%YAML 1.2
---

distribution_name: 'SunnyOS'

scripts:
  prepare: /etc/os-installer/scripts/prepare.sh
  install: /etc/os-installer/scripts/install.sh
  configure: /etc/os-installer/scripts/configure.sh

internet:
  connection_required: yes
  checker_url: 'http://nmcheck.gnome.org/check_network_status.txt'

fixed_language: no

welcome_page:
    logo    : '/usr/share/icons/sunnyos-logo-feather.png'
    text    : 'Welcome to SunnyOS!'
    usage   : yes

disk:
  partition_ok: yes
  min_size: 20

disk_encryption:
  offered: yes
  forced: no
  min_length: 1
  confirmation: yes

desktop:
  - name        : 'GNOME'
    description : 'Simple desktop that can be personalized with extensions.'
    image_path  : '/etc/os-installer/bits/gnome.png'
    keyword     : 'gnome'
  - name        : 'KDE Plasma'
    description : 'Configurable desktop that is similar to Windows.'
    image_path  : '/etc/os-installer/bits/plasma.png'
    keyword     : 'kde'
  - name        : 'Hyprland'
    description : 'WIP!!!'
    image_path  : '/usr/share/icons/hicolor/scalable/apps/qv4l2.svg' # TEMP
    keyword     : 'hyprland'

user:
  request_username: yes
  provide_autologin: yes
  min_password_length: 1
  password_confirmation: yes

skip_user: no
skip_locale: no

additional_software: []

additional_features: []

install_slideshow: []

failure_help_url: 'https://github.com/openai-ae/SunnyOS/issues'

commands:
  browser: 'firefox'
  disks  : 'gnome-disks'
  reboot : 'shutdown -r now'
  wifi   : 'gnome-control-center network'
